spring.application.name=hosManage

# PostgreSQL Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/Hospital_Management
spring.datasource.username=postgres
spring.datasource.password=Sarvesh@123

# Hibernate DDL generation (updates schema without wiping data)
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in the console
spring.jpa.show-sql=true

# Beautifully format the console SQL logs
spring.jpa.properties.hibernate.format_sql=true

# Explicit Database Dialect for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


logging.level.org.hibernate.orm.results=DEBUG


# ? NAYI SETTINGS: In dono lines ki wajah se data.sql chalega
# 1. Spring ko force karna ki data initialization hamesha chalaye
spring.sql.init.mode=always

# 2. Hibernate ko pehle tables 'update' karne dena, uske BAAD data.sql chalana
spring.jpa.defer-datasource-initialization=true



spring.mvc.pathmatch.use-suffix-pattern=false
springdoc.api-docs.enabled=true
spring.mvc.contentnegotiation.favor-path-extension=false


